### ISSUE TITLE
warning: requestLayout() improperly called by com.ramotion.circlemenu.RingEffectView

### ISSUE THREAD

**Issue by davidkhala** [Ramotion/circle-menu-android#12]
I saw of warnings below when using 
> W/View: requestLayout() improperly called by com.ramotion.circlemenu.RingEffectView{7c0ea4 V.ED..... ......ID 0,-644-1019,1664 #7f090074 app:id/ring_view} during layout: running second layout pass
> W/View: requestLayout() improperly called by com.ramotion.circlemenu.RingEffectView{7c0ea4 V.ED..... ........ 0,0-1019,1019 #7f090074 app:id/ring_view} during second layout pass: posting in next frame
> W/View: requestLayout() improperly called by com.ramotion.circlemenu.RingEffectView{7c0ea4 V.ED..... ......I. 0,0-1019,1019 #7f090074 app:id/ring_view} during layout: running second layout pass
> W/View: requestLayout() improperly called by com.ramotion.circlemenu.RingEffectView{7c0ea4 V.ED..... ........ 0,0-1019,1019 #7f090074 app:id/ring_view} during second layout pass: posting in next frame
> W/View: requestLayout() improperly called by com.ramotion.circlemenu.RingEffectView{7c0ea4 V.ED..... ......I. 0,0-1019,1019 #7f090074 app:id/ring_view} during layout: running second layout pass
> W/View: requestLayout() improperly called by com.ramotion.circlemenu.RingEffectView{7c0ea4 V.ED..... ......I. 0,0-1019,1019 #7f090074 app:id/ring_view} during second layout pass: posting in next frame
> W/View: requestLayout() improperly called by com.ramotion.circlemenu.RingEffectView{7c0ea4 V.ED..... ......I. 0,0-1019,1019 #7f090074 app:id/ring_view} during layout: running second layout pass

In some use case I even see this type of warning prompt repeatedly infinitely. 
My device and buidTarget version is 26

**Comment by dvg4000** [comment]
Thanks! I will try to fix it soon.
