### ISSUE TITLE
Icon Size

### ISSUE THREAD

**Issue by Ahsan221B** [Ramotion/circle-menu-android#16]
How can I make my icons look bigger? I don't need a color background, I want my icon to cover the whole background.
![26913809_1987449528190615_58996365_n](https://user-images.githubusercontent.com/18204579/34938309-b838f432-fa09-11e7-9a4d-b0923f81b107.png)

**Comment by dvg4000** [comment]
You can add this string to your `res/values/dimens.xml` file:
```xml
<dimen name="design_fab_image_size" tools:override="true">56dp</dimen>
```
But it will affects menu button too (and all other FAB in project), so you will have to use custom icons for that buttons.

**Comment by Ahsan221B** [comment]
@dvg4000 is there any other way by which I can specify exact height and width for the icon?

**Comment by Ahsan221B** [comment]
@dvg4000 is there any other way by which I can specify exact height and width for the icon?

**Comment by dvg4000** [comment]
@Ahsan221B no, our library does not support images as background and custom sizes for icons.

**Comment by tsikuratiyu** [comment]
((FloatingActionButton) b).setScaleType(ImageView.ScaleType.CENTER);  

This line, may be solution for icon size

**Comment by Ahsan221B** [comment]
@tsikuratiyu alright I'll try.
