### ISSUE TITLE
Change icons with code

### ISSUE THREAD

**Issue by 024N** [Ramotion/circle-menu-android#18]
Hi, I want to change icons and colors in mainactivity. Is it possbile?
I don't want to use xml part for icons and colors.
app:button_colors="@array/colors"
app:button_icons="@array/icons"

**Comment by dvg4000** [comment]
You can set icons and colors of icons only with xml constructor or with this constructor:
```java
public CircleMenuView(@NonNull Context context, @NonNull List<Integer> icons, @NonNull List<Integer> colors) 
```

Here is an example: https://github.com/Ramotion/circle-menu-android/issues/11#issuecomment-353277253
