### ISSUE TITLE
How i can set start angle and end angle like in iOS will you please provide some guideline.

### ISSUE THREAD

**Issue by Sumit-2singh** [Ramotion/circle-menu-android#23]
Hi @RamotionDev  
Thanks for providing us a attractive circle menu. currently i am facing a problem due to some design  changes Please check below screen shot i have done in iOS need to do same in Android too.

![screen shot 2018-05-08 at 11 41 01 am](https://user-images.githubusercontent.com/33151307/39740845-171d5aca-52b5-11e8-8feb-faf61a106af3.png)
 is it possible in android .

**Comment by dvg4000** [comment]
Hi @Sumit-2singh. No, CircleMenuView does not support this feature.

**Comment by Sumit-2singh** [comment]
Thanks @dvg4000  for quick replay , i have tried to make changes in library file some how it is working but start angle is not coming properly
