### ISSUE TITLE
[Question] Enable/Disable Buttons

### ISSUE THREAD

**Issue by TurKurT656** [Ramotion/circle-menu-android#24]
Hi, Thnx for this amazing library.
How we can enable/disable options of buttons in java and xml?

**Comment by TurKurT656** [comment]
I've tried this:
```
val video = options.getChildAt(3)
video.isEnabled = false
```

**Comment by golovin47** [comment]
Hello, @TurKurT656. You were on the right track, but instead of isEnabled, use clickable and longClickable like this:

menu.getChildAt(3).setClickable(false);
menu.getChildAt(3).setLongClickable(false);
