### ISSUE TITLE
Can we add text to the icons?

### ISSUE THREAD

**Issue by nandinicbit1981** [Ramotion/circle-menu-android#25]
is there a way to add text to icons?

**Comment by dvg4000** [comment]
No.

**Comment by nandinicbit1981** [comment]
Actually, i was able to, i made update to the library and i was able to add icons+text. So if anyone is interested in this, reach out to me at nandinicbit@gmail.com

**Comment by amirmollaee1369** [comment]
nandinicbit1981 put that's update here
thank you

**Comment by molekulyazilim** [comment]
+1
Did you find a solution related to this topic?
