### ISSUE TITLE
Manifest merger failed with minSdkVersion 21, targetSdkVersion 28

### ISSUE THREAD

**Issue by ghost** [Ramotion/circle-menu-android#33]
A pity, looked like a nice menu

```
Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.1.0-alpha03] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:12:5-40:19 to override.

```

**Comment by golovin47** [comment]
Hello, @bmalex88. This lib's most recent version was migrated to androidX. If you want to use it, you may migrate your project to androidX also. Another option is to use previous version of this lib. And third option is to do what this log suggests. You may look [here](https://stackoverflow.com/questions/50782435/android-design-support-library-for-api-28-p-not-working).

**Comment by uzaysan** [comment]
@golovin47 releases page is empty what is previous version?

**Comment by golovin47** [comment]
Hello, @uzaysan. 0.3.1 doesn't use androidx.
