### ISSUE TITLE
could not setbackground insteed of setIcon for buttons 

### ISSUE THREAD

**Issue by milrad53** [Ramotion/circle-menu-android#34]
Hello there
i wanna use your library for my project and i wanna setBackground for my buttons isteed of icons because icon showes my icon picture small but i wanna show them bigger

**Comment by golovin47** [comment]
Hello, @milrad53. Readme section of this library, explains how to use it. Also, you can check example app in this repo. If you need some additional features, you're welcome to fork this lib and customize it the way you need.
