### ISSUE TITLE
can i only display icon without color?

### ISSUE THREAD

**Issue by Anggyanisa** [Ramotion/circle-menu-android#42]
I want to make my menu display only display the icon. or can I increase the icon size? or reduce the color size?

**Comment by golovin47** [comment]
Hi, @Anggyanisa. You can try to set transparent color.

**Comment by Anggyanisa** [comment]
can i resize the drawable icon? if i can, where is the setting?

Pada tanggal Sel, 25 Feb 2020 pukul 14.58 golovin47 <
notifications@github.com> menulis:

**Comment by IvanGolovinYH** [comment]
Hi @Anggyanisa. Everything you can do with this lib out of the box described in readme section. If you need additional behavior you can fork it and modify the way you want.

**Comment by golovin47** [comment]
Hi @Anggyanisa. Everything you can do with this lib out of the box described in readme section. If you need additional behavior you can fork it and modify the way you want.
