### ISSUE TITLE
Open method Not working Properly Please Update 

### ISSUE THREAD

**Issue by sahilwebmazix** [Ramotion/circle-menu-android#7]
Hello i tried Open method of menu . but its not showing  all options its showing only 3 menu buttons with very bad Look and feed 
below is screen shot attached please check  
![screenshot_1512374341](https://user-images.githubusercontent.com/22518814/33541979-2cec5a6e-d8f7-11e7-8429-c62cfa65e586.png)

**Comment by dvg4000** [comment]
@sahilwebmazix, I can't reproduce your issue. Can you please show your `layout`?

**Comment by sahilwebmazix** [comment]
<com.ramotion.circlemenu.CircleMenuView
                android:id="@+id/circle_menu"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_centerInParent="true"
                app:button_colors="@array/colors"
                app:button_icons="@array/icons"
                app:icon_color="@color/color_share_bg"
                app:icon_menu="@drawable/ic_menu_share" />
     
<array name="icons">
        <item>@drawable/you_icon</item>
        <item>@drawable/f_icon</item>
        <item>@drawable/g_icon</item>
        <item>@drawable/t_icon</item>
        <item>@drawable/p_icon</item>
        <item>@drawable/inst_icon</item>
        <item>@drawable/v_icon</item>
        <item>@drawable/whatsapp_icon</item>
    </array>
    <array name="colors">
        <item>@color/color_youtube</item>
        <item>@color/color_fb</item>
        <item>@color/color_gplus</item>
        <item>@color/color_tweeter</item>
        <item>@color/color_pindrop</item>
        <item>@color/color_intragram</item>
        <item>@color/color_vin</item>
        <item>@color/color_whatsapp</item>
    </array>

final CircleMenuView menu = (CircleMenuView) dialogView.findViewById(R.id.circle_menu);
        menu.open(true);

**Comment by dvg4000** [comment]
Try this code, if you want to open menu on dialog creation. Also update `circle-menu` to `0.2.1` version.

```java
public class CircleMenuDialog extends DialogFragment {

 ...

 @Override
    public void onViewCreated(View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);

        final CircleMenuView menu = view.findViewById(R.id.circle_menu);
        menu.getViewTreeObserver().addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener() {
            @Override
            public void onGlobalLayout() {
                menu.getViewTreeObserver().removeOnGlobalLayoutListener(this);
                menu.open(true);
            }
        });
    }

 ...

```

**Comment by sahilwebmazix** [comment]
Thanks  a lot  @dvg4000   Its working now  :)

**Comment by pourya0111** [comment]
@sahilwebmazix hey there i just loved your play icon (cyan) very much, in center of that card view is it possible to share it?
thanks
