### ISSUE TITLE
error inflating com.ramotion.circlemenuview

### ISSUE THREAD

**Issue by merovic** [Ramotion/circle-menu-android#9]

**Comment by dvg4000** [comment]
Any error messages?

**Comment by merovic** [comment]
android.view.InflateException: Binary XML file line #10: Binary XML file line #10: Error inflating class com.ramotion.circlemenu.CircleMenuView

**Comment by dvg4000** [comment]
Can you please provide part of your xml-layout, where you use `CircleMenuView`?  I can't reproduce your error. Here is my working test layout:

```xml
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="#74009dff"
    xmlns:app="http://schemas.android.com/apk/res-auto">

    <com.ramotion.circlemenu.CircleMenuView
        android:id="@+id/circle_menu"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="center"
        app:button_colors="@array/colors"
        app:button_icons="@array/icons"/>

</FrameLayout>
```

**Comment by jihedjaouadi** [comment]
Hello !! I have the same issue, I got ;
[ android.view.InflateException: Binary XML file line #0: Error inflating class com.ramotion.circlemenu.CircleMenuView"]

 Any idea which the cause is ? I'm using it inside a full view of camera preview.

**Comment by dvg4000** [comment]
@jihedjaouadi can you give error logs and your xml layout?

**Comment by swivermobile** [comment]
Hello I have the same issue : [ android.view.InflateException: Binary XML file line #0: Error inflating class com.ramotion.circlemenu.CircleMenuView]  any help please?? 

`<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="#74009dff"
    xmlns:app="http://schemas.android.com/apk/res-auto">

    <com.ramotion.circlemenu.CircleMenuView
        android:id="@+id/circle_menu"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="center"
        app:button_colors="@array/colors"
        app:button_icons="@array/icons"/>

</FrameLayout>`

**Comment by teganburns** [comment]
You need to add the buttons.xml file under res. Then assign icons to the items.

**Comment by Pinjari** [comment]
@teganburns 
buttons.xml  is already there in values folder but still same error

**Comment by golovin47** [comment]
Hello, @merovic, @Pinjari, @swivermobile, @jihedjaouadi. We can't reproduce this issue. In order to resolve it, please do the following:
1. Read the Readme of this lib more carefully and follow the steps, described there.
2. If this issue still appears, provide us with as much detailed info as possible including source code, layout.xml and buttons.xml.

Until then this issue is considered as closed.
